### PR TITLE
Automated PR: Cookstyle Changes

### PR DESCRIPTION
**Pull request by xorimabot**
Hey!
I ran Cookstyle 6.13.3 against this repo and here are the results.
This repo was selected due to the topics of chef-cookbook

### Issues found and resolved with libraries/provider_carbon_conf_accumulator.rb

 - 37:7 refactor: `ChefModernize/ActionMethodInResource` - Use the custom resource language's `action :my_action` blocks instead of creating actions with methods.

### Issues found and resolved with libraries/provider_storage_conf_accumulator.rb

 - 37:7 refactor: `ChefModernize/ActionMethodInResource` - Use the custom resource language's `action :my_action` blocks instead of creating actions with methods.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
Looks like the chefspec fails only on Chef 16. Works fine on Chef 15. Not sure if we should try and fix that here or not.

**Comment by Xorima** [comment]
@tas50 do you know what would have changed to cause this failure?

**Comment by ramereth** [comment]
> @tas50 do you know what would have changed to cause this failure?

@tas50 reping :)

**Comment by tas50** [comment]
I think the funky accumulator pattern here and the method actions are required

**Comment by ramereth** [comment]
> I think the funky accumulator pattern here and the method actions are required

@tas50 so we should tell cookstyle to ignore those and close this PR?

**Comment by tas50** [comment]
Yeah I think we have to disable those for this cookbook.

**Pull request closed without merging**
